### ISSUE TITLE
Loading BNM

### ISSUE THREAD

**Issue by WoozyDev** [ByNameModding/BNM-Android#17]
How can i load BNM if i already have a base address? I'm internal. And somehow i can't acess BNM_Internal.

**Comment by WoozyDev** [comment]
@BNM-Dev

**Comment by BNM-Dev** [comment]
`BNM_Internal` is BNM's internal data. To load it, you can uncomment `BNM_DISABLE_AUTO_LOAD` or call `TryForceLoadIl2CppByPath` from JNI_OnLoad (this way better, due to only one call).
