### ISSUE TITLE
Overloaded Method

### ISSUE THREAD

**Issue by ArifRios1st** [ByNameModding/BNM-Android#23]
how to hook method that have same name and params count but different type ?

`// RVA: 0x8BD0E0 Offset: 0x8BD0E0 VA: 0x8BD0E0 Slot: 17`
`public void TargetMove(float speed, Transform targetTransform, float range, Action endCallBack) { }`

`// RVA: 0x8BD1E0 Offset: 0x8BD1E0 VA: 0x8BD1E0`
`public void TargetMove(float speed, Vector3 position, float range, Action endCallBack) { }`

**Comment by ArifRios1st** [comment]
ah i don't know there is GetMethodByName by paramName and paramType
sorry

**Comment by ArifRios1st** [comment]
how to hook something like this ?
![image](https://github.com/ByNameModding/BNM-Android/assets/32938569/bbedbc86-bd29-4c78-9b81-a1b11e5bfe23)
i want to hook both
can you give example, because it same params count and params name
@BNM-Dev

**Comment by BNM-Dev** [comment]
I don't know all paths to classes, so you will need add them. But code should work. (At least for `AddRate` with float)
```cpp
auto cls = LoadClass("", ""); // Class with AddRate methods
auto calcStep = LoadClass("", "SkillCalcTemplate").GetInnerClass("CalcStep");
auto floatType = BNM::GetType<float>();
auto funcCls = LoadClass("", "Func`1"); // Idk full path to Func class
auto  funcFloatCls = funcCls.GetGeneric({floatType}); // Func<float>

auto met1 = cls.GetMethodByName("AddRate", {calcStep, funcFloatCls}); // AddRate with Func<float>
auto met2 = cls.GetMethodByName("AddRate", {calcStep, floatType}); // AddRate with float
```

**Comment by ArifRios1st** [comment]
Thanks, work like charm !!

**Comment by dvgmdvgm** [comment]
@BNM-Dev @ArifRios1st hello
Looks strange for me.
I have two methods which is completely same except the args type:
`public void .ctor(string value) { }

	
	public void .ctor(byte[] value) { }`

Trying to hook second one (byte[]) by this snippet:
`auto bytesType = GetType<byte[]>();
    auto met_ctor = MyClass.GetMethodByName(".ctor", {bytesType});`

and get following log output:
Method: [NameSpace]::[Classs].[.ctor], 1 - not found; using parameter types.

**Comment by ArifRios1st** [comment]
> @BNM-Dev @ArifRios1st hello Looks strange for me. I have two methods which is completely same except the args type:
> 
> ![Screen-074](https://private-user-images.githubusercontent.com/20095457/302011204-20b417d2-b43a-419b-94db-253a8b403e0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjMxNDIsIm5iZiI6MTcwNjk2Mjg0MiwicGF0aCI6Ii8yMDA5NTQ1Ny8zMDIwMTEyMDQtMjBiNDE3ZDItYjQzYS00MTliLTk0ZGItMjUzYThiNDAzZTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDEyMjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzQ2ZGE2MzNlMDI4MTkwOTRiOTk2ZDgxNDcyNmJmNmM4MzU4Njc1OTRmY2E2NjkwOWI3MmZmZWVjMjFmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uU6BkCO2M-JXAJ1yWysmElkq92sKoQ38CpZqh--kkqA)
> 
> Trying to hook second one (byte[]) by this snippet: `auto bytesType = GetType<byte[]>(); auto met_ctor = MyClass.GetMethodByName(".ctor", {bytesType});`
> 
> Also trying GetType<uint8_t>();
> 
> and get following log output: Method: [NameSpace]::[Classs].[.ctor], 1 - not found; using parameter types.

i think it should be like `auto arrayOfByte = BNM::GetType<uint8_t>(RuntimeTypeGetter::RuntimeModifier::Array);` then `auto met_ctor = MyClass.GetMethodByName(".ctor", {arrayOfByte});`

**Comment by dvgmdvgm** [comment]
> > @BNM-Dev @ArifRios1st hello Looks strange for me. I have two methods which is completely same except the args type:
> > ![Screen-074](https://private-user-images.githubusercontent.com/20095457/302011204-20b417d2-b43a-419b-94db-253a8b403e0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NjMxNDIsIm5iZiI6MTcwNjk2Mjg0MiwicGF0aCI6Ii8yMDA5NTQ1Ny8zMDIwMTEyMDQtMjBiNDE3ZDItYjQzYS00MTliLTk0ZGItMjUzYThiNDAzZTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDEyMjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYzQ2ZGE2MzNlMDI4MTkwOTRiOTk2ZDgxNDcyNmJmNmM4MzU4Njc1OTRmY2E2NjkwOWI3MmZmZWVjMjFmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uU6BkCO2M-JXAJ1yWysmElkq92sKoQ38CpZqh--kkqA)
> > Trying to hook second one (byte[]) by this snippet: `auto bytesType = GetType<byte[]>(); auto met_ctor = MyClass.GetMethodByName(".ctor", {bytesType});`
> > Also trying GetType<uint8_t>();
> > and get following log output: Method: [NameSpace]::[Classs].[.ctor], 1 - not found; using parameter types.
> 
> i think it should be like `auto arrayOfByte = BNM::GetType<uint8_t>(RuntimeTypeGetter::RuntimeModifier::Array);` then `auto met_ctor = MyClass.GetMethodByName(".ctor", {arrayOfByte});`

working perfectly. Can i ask for your discord please. Cause i have one or two more questions about this method

**Comment by dvgmdvgm** [comment]
@ArifRios1st or may be you can help me here?
Because i need to read this byte[] as string. 
I was possible by Frida with this snippet:
`Memory.readUtf8String(value.add(0x20), Memory.readInt(value.add(0x18)))`

**Comment by doviettung96** [comment]
Hi guys, then I have this case
public DynValue Call(params object[] args)
{
	return null;
}
this is from moonsharp.intepreter.Closure. I also need to overload thif function and call. However, when I call it, my game crashes.
