### ISSUE TITLE
Создание нового экземпляра класса

### ISSUE THREAD

**Issue by mindcodd3r** [ByNameModding/BNM-Android#25]
Хочу создать экземпляр класса игры, передав свои параметры, как такое сделать?

**Comment by ArifRios1st** [comment]
может быть что-то вроде этого?

`BNM::LoadClass PlayerClass = BNM::LoadClass(OBFUSCATE_BNM(""),OBFUSCATE_BNM("PlayerClass"));`
`void* newPlayerClass = PlayerClass.CreateNewObject();`
