### ISSUE TITLE
Question: How to get value of "int" field of another class?

### ISSUE THREAD

**Issue by dvgmdvgm** [ByNameModding/BNM-Android#26]
Hello. 
I have some fighting Unity game.
And every hit is calling method "void CritChance(void* attribute)"
I need to read field of this attribute and after read another int value from another filed. Before I use frida script and my snippet looks like that:
`int player_id = Memory.readInt(Memory.readPointer(attribute.add(0x38)).add(0x8));`

Which "add(0x38)" is field of current class.
"add(0x8)" is <int>field of other class called.

How can I achieve it with BNM?
If you need I can show some part of dump of il2cpp.
Thank you.

**Comment by ArifRios1st** [comment]
maybe i can help,
you can do like this :
`void* attributeClass = *(void **)((uint64_t)attribute+ 0x38);`
`int player_id = *(int*)((uint64_t)()+ 0x8);`

or with bnm maybe you can do like this :
`BNM::LoadClass attributeClass = BNM::LoadClass((BNM::IL2CPP::Il2CppObject*)attribute);`
`int player_id = RoomDatabaseClass.GetFieldByName(OBFUSCATE_BNM("player_id")).cast<int>().Get();`

**Comment by dvgmdvgm** [comment]
> maybe i can help, you can do like this : `void* attributeClass = *(void **)((uint64_t)attribute+ 0x38);` `int player_id = *(int*)((uint64_t)()+ 0x8);`
> 
> or with bnm maybe you can do like this : `BNM::LoadClass attributeClass = BNM::LoadClass((BNM::IL2CPP::Il2CppObject*)attribute);` `int player_id = RoomDatabaseClass.GetFieldByName(OBFUSCATE_BNM("player_id")).cast<int>().Get();`

1st example working great.
May be you can help me how to invoke non static method but with Instance?
I know that i need to use instance of class to call this method but i'm very first with C++ hooking on Android.
For example i have class:
 `public class Manager
{
	// Fields
        private bool _isLoaded; // 0x28
	
	// Properties
	public static GameModeManager Instance { get; }

	// Methods
	public static Manager get_Instance() { }
        public void LoadMap() { }
}
`

As i understand i have to call LoadMap method like this:
`ManagerClass.LoadMap(get_Instance());`
But how to reproduce it with BNM?

Thank you

**Comment by ArifRios1st** [comment]
> > maybe i can help, you can do like this : `void* attributeClass = *(void **)((uint64_t)attribute+ 0x38);` `int player_id = *(int*)((uint64_t)()+ 0x8);`
> > or with bnm maybe you can do like this : `BNM::LoadClass attributeClass = BNM::LoadClass((BNM::IL2CPP::Il2CppObject*)attribute);` `int player_id = RoomDatabaseClass.GetFieldByName(OBFUSCATE_BNM("player_id")).cast<int>().Get();`
> 
> 1st example working great. May be you can help me how to invoke non static method but with Instance? I know that i need to use instance of class to call this method but i'm very first with C++ hooking on Android. For example i have class:
> 
> ![Screen-072](https://private-user-images.githubusercontent.com/20095457/301994000-ef461705-0420-4aba-a295-bcbf41ed0298.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTY4MjEsIm5iZiI6MTcwNjk1NjUyMSwicGF0aCI6Ii8yMDA5NTQ1Ny8zMDE5OTQwMDAtZWY0NjE3MDUtMDQyMC00YWJhLWEyOTUtYmNiZjQxZWQwMjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDEwMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjI3NmViZDRiYTY1YjhjMTFhYTc3ZWMxZjkxNTZjZjk2ZDYzNjhlZGZhN2QzYjdmODY4YTBjZGEzNmQxNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DMxs4FLr1BMHFCqOF3CSMpU8iNYAmAJK_EH0PkWqdN0)
> 
> As i understand i have to call LoadMap method like this: `get_Instance().method(LoadMap).Call();` But how to reproduce it with BNM?
> 
> Thank you

if Instance is property, you can do
`BNM::LoadClass ManagerClass = LoadClass("", "Manager");`
`BNM::Property<BNM::IL2CPP::Il2CppObject*> Manager$$Instance = ManagerClass.GetPropertyByName("Instance");`
`BNM::Method<void> Manager$$LoadMap = ManagerClass.GetMethodByName("LoadMap",0); `

because is static you can direcly call it
`BNM::IL2CPP::Il2CppObject* Instance = Manager$$Instance.Get();`

and then call LoadMap method
`Manager$$LoadMap[Instance]();` or `Manager$$LoadMap.SetInstance(Instance).Call();`
