### ISSUE TITLE
Any chance to call Java method of hooked game?

### ISSUE THREAD

**Issue by dvgmdvgm** [ByNameModding/BNM-Android#29]
Hello. I want to call some Java method of hooking game from BNM. How can i achieve it?
For example:
`class = com.game..Util;
methodToast = class.showToast;
methodToast("MOD by Bruno");
`

**Comment by BNM-Dev** [comment]
2 ways:
1. BNM less - [JNI](https://developer.android.com/training/articles/perf-jni).
2. With BNM - [Unity's AndroidJNI](https://docs.unity3d.com/ScriptReference/AndroidJNI.html), that just wrapper for JNI, so better is just use JNI.
