### ISSUE TITLE
Can load BNM Extenally using KittyMemory instead ?

### ISSUE THREAD

**Issue by ArifRios1st** [ByNameModding/BNM-Android#30]
because KittyMemory have [findSymbol](https://github.com/MJx0/KittyMemory/blob/b852955be8434f4e19e28816a55a9ae2ab582a8b/example-android/example.cpp#L75) like that, can i just use that instead ? what must be replace to load BNM Externally ?

**Comment by ArifRios1st** [comment]
after try it,
i make custom SetupBNM `void SetupBNMKittyMemory(ElfScanner il2cppScan)` and have to replace all that use il2cppLibraryHandle using ElfScanner from KittyMemory
example:
`(BNM_PTR) BNM_dlsym(il2cppLibraryHandle, OBFUSCATE_BNM("il2cpp_array_new_specific"))` to `(BNM_PTR) il2cppScan.findSymbol(OBFUSCATE_BNM("il2cpp_array_new_specific"))`

then make exxternal function to load
`void LoadKittyMemory(ElfScanner ilcppScan) {`
`      BNM_Internal::il2cppLibraryAbsolutePath = ilcppScan.filePath().c_str();`
`      BNM_Internal::il2cppLibraryAbsoluteAddress = (BNM_PTR) ilcppScan.base();`
`      BNM_Internal::SetupBNMKittyMemory(ilcppScan);`
`      bnmLoaded = true;`
`}`

and load it like this
`do {`
`    sleep(1);`
`    g_il2cppELF = ElfScanner::createWithPath("libil2cpp.so");`
`} while (!g_il2cppELF.isValid());`
BNM::External::LoadKittyMemory(g_il2cppELF);

and all work properly !

**Comment by ArifRios1st** [comment]
1 more question @BNM-Dev 
for load BNM Externaly, is that need to use `BNM::AttachIl2Cpp();` and `BNM::DetachIl2Cpp();` ?

**Comment by BNM-Dev** [comment]
`AttachIl2Cpp` and `DetachIl2Cpp` are deprecated. Just hook Start/Awake or any other method in game and setup/find all things in it.

About finding symbols, I think in BNM v2.0 I will create sth like system for finding them by user defined code.

**Comment by solomode0001** [comment]
So, when will BNM v2.0 be released? I'm really excited and can't wait for it. Just to let you know, I check this page almost every day to see if BNM v2.0 has been released yet because I really love this library.

**Comment by ArifRios1st** [comment]
> About finding symbols, I think in BNM v2.0 I will create sth like system for finding them by user defined code.

nice one, i can't wait for v2.0

**Comment by BNM-Dev** [comment]
> So, when will BNM v2.0 be released? I'm really excited and can't wait for it. Just to let you know, I check this page almost every day to see if BNM v2.0 has been released yet because I really love this library.

I now just have no time to complete all things.

**Comment by solomode0001** [comment]
> > So, when will BNM v2.0 be released? I'm really excited and can't wait for it. Just to let you know, I check this page almost every day to see if BNM v2.0 has been released yet because I really love this library.
> 
> I now just have no time to complete all things.


It's okay, sir, don't force yourself. Enjoy your time in the real world. When you're feeling up to it, we can resume our project. I'll be here waiting patiently. May God grant you a long life, abundant blessings, and prosperity.

**Comment by chiteroman** [comment]
I recommend using xDL to load il2cpp: https://github.com/hexhacking/xDL

Also @BNM-Dev take a look to shadowhook: https://github.com/bytedance/android-inline-hook I think is better than Dobby.
