### ISSUE TITLE
BNM_NewStaticMethodInit problem

### ISSUE THREAD

**Issue by ArifRios1st** [ByNameModding/BNM-Android#31]
i make new class something like this

```
struct PlayerData : public BNM::UnityEngine::MonoBehaviour {
   BNM_NewClassInit("NewClass", PlayerData, {
      return BNM::LoadClass(OBFUSCATES_BNM("UnityEngine"), 
         OBFUSCATES_BNM("MonoBehaviour"), 
         OBFUSCATES_BNM("UnityEngine.CoreModule"));
         }
      );
        
   static bool Move(BNM::Structures::Unity::Vector3 pos){
        //do something
        return true;
   }
   BNM_NewStaticMethodInit(BNM::GetType<bool>(), Move, 1, BNM::GetType<BNM::Structures::Unity::Vector3>());
}
```

in `BNM_NewStaticMethodInit(BNM::GetType<bool>(), Move, 1, BNM::GetType<BNM::Structures::Unity::Vector3>());`
i got error `In template: cannot initialize return object of type 'void *' with an rvalue of type 'bool'`

can you help me ? @BNM-Dev

**Comment by BNM-Dev** [comment]
This thing don't exists in BNM v2.0, so wait for update.

**Comment by BNM-Dev** [comment]
New API will look like this:
```cpp
struct PlayerData : public BNM::UnityEngine::MonoBehaviour {
    BNM_CustomClass(PlayerData,
                    BNM::CompileTimeClassBuilder().Class(OBFUSCATE_BNM("NewClass")).Build(),
                    BNM::CompileTimeClassBuilder().Class(OBFUSCATE_BNM("MonoBehaviour"), OBFUSCATE_BNM("UnityEngine"), OBFUSCATE_BNM("UnityEngine.CoreModule")).Build(),
                    {}
    );
    
    static bool Move(BNM::Structures::Unity::Vector3 pos) {
        // Do something
        return true;
    }
    
    BNM_CustomMethod(Move, true, BNM::GetType<bool>(), "Move", BNM::GetType<BNM::Structures::Unity::Vector3>());
};
```

**Comment by solomode0001** [comment]
> New API will look like this:
> 
> ```c++
> struct PlayerData : public BNM::UnityEngine::MonoBehaviour {
>     BNM_CustomClass(PlayerData,
>                     BNM::CompileTimeClassBuilder().Class(OBFUSCATE_BNM("NewClass")).Build(),
>                     BNM::CompileTimeClassBuilder().Class(OBFUSCATE_BNM("MonoBehaviour"), OBFUSCATE_BNM("UnityEngine"), OBFUSCATE_BNM("UnityEngine.CoreModule")).Build(),
>                     {}
>     );
>     
>     static bool Move(BNM::Structures::Unity::Vector3 pos) {
>         // Do something
>         return true;
>     }
>     
>     BNM_CustomMethod(Move, true, BNM::GetType<bool>(), "Move", BNM::GetType<BNM::Structures::Unity::Vector3>());
> };
> ```

I'm so excited for the update!

**Comment by BNM-Dev** [comment]
v2.0 is out, so I closing this issue.
