### ISSUE TITLE
[Need help]What, Hook's the type?

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#32]
public static bool[] NurseCannotRemoveDebuff = BuffID.Sets.Factory.CreateBoolSet(new int[]{28, 34, 87, 89, 21, 86, 199, 332, 333, 334, 165, 146, 48, 158, 157, 350, 215, 147);

**Comment by 2079541547** [comment]
I did some research and found that the data for this is in global-metadata.dat, will this affect the hook?
我研究了一下，发现这东西的数据在global-metadata.dat里面有，这样会不会影响hook?

**Comment by 2079541547** [comment]
The code is decompiled from the computer side (mono architecture), can it be used for mobile Hook (the code is basically the same)
代码是电脑端(mono架构)反编译出来的，是否可以用于手机端的Hook（代码基本一致）

**Comment by BNM-Dev** [comment]
> I did some research and found that the data for this is in global-metadata.dat, will this affect the hook?

If `NurseCannotRemoveDebuff` is static then, it should be set in `.cctor`. So this is possible to hook `CreateBoolSet` and change value or hook `.cctor` of class that contains `NurseCannotRemoveDebuff` to change it later. 

> The code is decompiled from the computer side (mono architecture), can it be used for mobile Hook (the code is basically the same)

There is no any problems with hooking something based on mono game version, I myself did this once too.

And write on English, I don't know Chinese very well.

**Comment by 2079541547** [comment]
感君一顾恩，同来洛阳陌
(Your glance, a gift of kindness, leads us to the fabled streets where Luoyang's history unfolds)
