### ISSUE TITLE
ARM32  game crashes

### ISSUE THREAD

**Issue by yunli97** [ByNameModding/BNM-Android#33]
![1715412476234](https://github.com/ByNameModding/BNM-Android/assets/152859080/7e9ef3d8-9e8f-45d6-b104-62917136a17d)

**Comment by yunli97** [comment]
UNITY_VER 222

**Comment by BNM-Dev** [comment]
Known, will be fixed in Release.

**Comment by BNM-Dev** [comment]
Try v2.0

**Comment by yunli97** [comment]
The crash issue has been resolved, thank you
