### ISSUE TITLE
Availability of Lua support ?

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#34]
Perhaps incorporating Lua libraries could simplify operations, as C++ can directly register functions in Lua, which might enable more operations.

**Comment by qqizai** [comment]
Similarly, I have also been injecting the method of combining LUA recently. At present, I have not yet understood how to use LUA injection. Does anyone come to study together?

**Comment by 2079541547** [comment]
Perhaps you could expose the API in C++ and then use Lua to call the

**Comment by BNM-Dev** [comment]
I think this is possible to add bindings to lua or any other scripting language, but this is not main thing that I want to do for BNM firstly.
