### ISSUE TITLE
How to invoke static method

### ISSUE THREAD

**Issue by ice5355** [ByNameModding/BNM-Android#36]
How to invoke static method in BNM , the c# code like
`var button3 = GameObject.Find("Button (3)");`

**Comment by ballsofsoul** [comment]
> assuming you are using latest BNM

1. Get Gameobject class
`auto GameObjectClass = BNM::Class("UnityEngine", "GameObject");`
2. Get needed method (Find) from class
`BNM::Method<void*> GameObject_Find = GameObjectClass.GetMethod("Find", 1);`
3. Call this method
`auto button3_go = GameObject_Find.Call(String::Create("Button (3)"));`

**Comment by ice5355** [comment]
Thank you!
