### ISSUE TITLE
How to specialize parameters?

### ISSUE THREAD

**Issue by ballsofsoul** [ByNameModding/BNM-Android#39]
`bool DoSomething(int, float, string);`

`BNM::Method<bool> DoSomethingByName;`

How to define parameters to pass in bnm method?

**Comment by Lsc0x80** [comment]
It's not required.
if you need to get a method with specific parameters if there are multiple methods with the same number of parameters check the method in `BNM::Class`:
```C++
BNM::MethodBase GetMethod(const std::string_view &name, const std::initializer_list<BNM::CompileTimeClass> &parametersType) const;
```

**Comment by ballsofsoul** [comment]
this is not possible with obfuscated method names, which was my case
