### ISSUE TITLE
How to hook static fields

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#43]
I want to do what the hook static field should do. The following is using Tool dump

![Screenshot_20240622_103704](https://github.com/ByNameModding/BNM-Android/assets/142726636/6003cf18-652b-4dc7-b400-88c944abbde3)
![Screenshot_20240622_103645](https://github.com/ByNameModding/BNM-Android/assets/142726636/1b3f57ad-0701-458f-865e-89e3494455ca)

**Comment by Lsc0x80** [comment]
```C++
//...
auto ItemID_Sets_c = BNM::Class("Terraria.ID", "ItemID").GetInnerClass("Sets");
BNM::Field<BNM::Mono::Array<bool>> Deprecated = ItemID_Sets_c.GetField("Deprecated");
for (const bool& a : Deprecated.Get()->ToVector())
{
    // Code that writes values to file
}
//...
```

**Comment by 2079541547** [comment]
Thank you, good comrade

**Comment by 2079541547** [comment]
I want to create a new field inside itemid and hook the switch branch of SetDefaults5 in item, I want to be able to call this.DefaultToAccessory(30, 42);
What can I do with code like this?
![image](https://github.com/ByNameModding/BNM-Android/assets/142726636/cea5b767-c45c-4f49-905a-de1e9819eed9)
![image](https://github.com/ByNameModding/BNM-Android/assets/142726636/3cb9697c-e474-4c2b-abb9-d503d2b3d585)
