### ISSUE TITLE
Can it work with zygisk module imgui on emulator  i try it crash

### ISSUE THREAD

**Issue by cykopean** [ByNameModding/BNM-Android#47]
my code some like this

```
void *hack_thread(void *arg) {
    do {
        sleep(1);
        g_il2cppBaseMap = KittyMemory::getLibraryBaseMap("libil2cpp.so");
    } while (!g_il2cppBaseMap.isValid());
    LOGI("il2cpp base: %p", (void*)(g_il2cppBaseMap.startAddress));


    BNM::Loading::AllowedLateInitHook();
    BNM::Loading::TryLoadByDlfcnHandle((void*)g_il2cppBaseMap.startAddress);
    BNM::Loading::AddOnLoadedEvent(MyHook);
}
```

**Comment by BNM-Dev** [comment]
Read [this](https://www.opennet.ru/man.shtml?topic=dlfcn.h) and then [this](https://github.com/ByNameModding/BNM-Android/blob/master/examples/07_CustomFinder.cpp) and after that ask questions if you still can't understand.

**Comment by Lsc0x80** [comment]
please post the solution if you can

**Comment by BNM-Dev** [comment]
> please post the solution if you can

Examples already contains solution.

**Comment by Lsc0x80** [comment]
you can try get java vms by making pointer to JNI_GetCreatedJavaVMS and call JNI_OnLoad
