### ISSUE TITLE
How to create an instance of a generic dictionary?

### ISSUE THREAD

**Issue by hontszpang** [ByNameModding/BNM-Android#48]
I tried to follow the example using "dictionaryClass.GetGeneric({BNM::GetType<int>(), BNM::GetType<int>()})" but it leads to the errors 
07-13 21:53:32.474 18414 18414 E MD      : An attempt to use dead class!
07-13 21:53:32.474 18414 18414 E MD      : Null object in the iterator
07-13 21:53:32.474 18414 18414 E MD      : An attempt to use dead class!
07-13 21:53:32.474 18414 18414 E MD      : Null object in the iterator

**Comment by BNM-Dev** [comment]
Try update BNM to v2.0.2
