### ISSUE TITLE
How to use shadowhook for hooks ?

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#52]
I've integrated shadowhook but I don't know how to use it for hooking, so I'm looking for a tutorial.

**Comment by BNM-Dev** [comment]
[Here](https://github.com/ByNameModding/BNM-Android/blob/a6aecea08b243bdd4fe93288778728da4cde51fe/include/BNM/UserSettings/GlobalSettings.hpp#L91)

**Comment by 2079541547** [comment]
Thank you comrade
