### ISSUE TITLE
How to use XDL

### ISSUE THREAD

**Issue by yunli97** [ByNameModding/BNM-Android#53]
i use xdl
![image](https://github.com/user-attachments/assets/52cc2f1f-1c48-4463-bf0b-fc6f530fbca5)
when i use  handle = xdl_open(lib_name, XDL_DEFAULT); 
![image](https://github.com/user-attachments/assets/6b2e2ff9-9391-4750-a10f-0dbb943b9d14)
when i use  handle = xdl_open(lib_name, XDL_TRY_FORCE_LOAD); But no HOOK(init, Internal::BNM_il2cpp_init, Internal::old_BNM_il2cpp_init) is executed;
![image](https://github.com/user-attachments/assets/14b359dd-34fb-4998-a301-d8e1a10de1bc)
![image](https://github.com/user-attachments/assets/d3f967e8-eae6-42f2-a6ba-3c50a9619ff6)
Which step did I go wrong?

**Comment by BNM-Dev** [comment]
Read [this](https://github.com/ByNameModding/BNM-Android/blob/a6aecea08b243bdd4fe93288778728da4cde51fe/include/BNM/Loading.hpp#L20) and [this](https://github.com/ByNameModding/BNM-Android/blob/a6aecea08b243bdd4fe93288778728da4cde51fe/examples/07_CustomFinder.cpp#L21)
