### ISSUE TITLE
I have a problem using lateInitAllowed

### ISSUE THREAD

**Issue by yunli97** [ByNameModding/BNM-Android#58]
![image](https://github.com/user-attachments/assets/fb93f327-1a02-4771-8f4f-a8b3dca4604c)
The location of the code crash is here
![image](https://github.com/user-attachments/assets/ff8714bf-eaab-4bbb-9bec-8625d8146814)

**Comment by BNM-Dev** [comment]
I think I know, I will fix this in next patch. Setup called inside il2cpp_init that resulted crash.

**Comment by BNM-Dev** [comment]
Try v2.0.3.

**Comment by yunli97** [comment]
I tried v2.0.3.A new CRASH problem 
![image](https://github.com/user-attachments/assets/ed9db90a-1654-49a1-9873-94549f0233d4)
Looking at the log it should be
 auto domain = il2cppMethods.il2cpp_domain_get(); 
that's causing the problem

**Comment by yunli97** [comment]
I think I know,  il2cpp_domain_get Not initialized yet

**Comment by BNM-Dev** [comment]
I will fix that
