### ISSUE TITLE
help I don't know if I'm doing it right?

### ISSUE THREAD

**Issue by EduModsS** [ByNameModding/BNM-Android#59]
```
	while (!libil2cpp) {
		libil2cpp = dlopen("libil2cpp.so", 4);
		sleep(1);
	}

//	BNM::Loading::AllowedLateInitHook();
	BNM::Loading::TryLoadByDlfcnHandle(libil2cpp);
```

its right? doing this in main thread, idk if i need to use AllowedLateInitHook or no, but when i use it says this, and crash:

```
07-30 20:27:21.208 29986 30087 D ByNameModding: [SetupBNM] il2cpp::vm::Class::Init in lib: 0x10f1c9c.
07-30 20:27:21.208 29986 30087 D ByNameModding: [SetupBNM] code has il2cpp_image_get_class. BNM will use it.
07-30 20:27:21.208 29986 30087 I dwygame.crisisx: [!] [/storage/emulated/0/AndroidIDEProjects/EduMods/app/src/main/cpp/ByNameModding/Dobby/source/InterceptRouting/Routing/FunctionInlineHook/FunctionInlineHook.cc:29:DobbyHook]0x777a533774 already been hooked.
07-30 20:27:21.208 29986 30087 D ByNameModding: [SetupBNM] il2cpp::vm::Class::FromIl2CppType in lib: 0x10f1774.
07-30 20:27:21.209 29986 30087 D ByNameModding: [SetupBNM] il2cpp::vm::Type::GetClassOrElementClass in lib: 0x10ddc24.
07-30 20:27:21.209 29986 30087 D ByNameModding: [SetupBNM] il2cpp::vm::Image::FromName in lib: 0x10d9e80.
07-30 20:27:21.209 29986 30087 D ByNameModding: [SetupBNM] il2cpp::vm::Assembly::GetAllAssemblies in lib: 0x105f5e4.
07-30 20:27:21.211 29986 30087 W ByNameModding: Class: [mscorlib.dll]::[System.Reflection]::[MonoMethod] - not found.
07-30 20:27:21.211 29986 30087 E ByNameModding: An attempt to use dead class!
07-30 20:27:21.212 29986 30087 W ByNameModding: Method: [System]::[Type].[GetType], 1 - not found
07-30 20:27:21.212 29986 30087 W ByNameModding: Method: [System.Threading]::[Interlocked].[CompareExchange], 3 - not found by arguments types.
07-30 20:27:21.212 29986 30087 W ByNameModding: Method: [System]::[RuntimeType].[MakeGenericType], 2 - not found
07-30 20:27:21.212 29986 30087 W ByNameModding: Method: [System]::[RuntimeType].[MakePointerType], 1 - not found
07-30 20:27:21.212 29986 30087 W ByNameModding: Method: [System]::[RuntimeType].[make_byref_type], 0 - not found
07-30 20:27:21.213 29986 30087 W ByNameModding: Field: [System]::[String].(Empty) - not found.
07-30 20:27:21.213 29986 30087 E ByNameModding: Null pointer to the field [Dead]
```

**Comment by EduModsS** [comment]
when "BNM::Loading::AllowedLateInitHook()" is commented, it starts, I just don't know if it does the hooks, I don't understand how I can do the hooks

**Comment by YummyBacon5** [comment]
> its right? doing this in main thread

Your `sleep` would block the main thread and stop the game from loading, so probably not.

> idk if i need to use AllowedLateInitHook or no

This needs to be used when the BNM loading happens after Unity's `il2cpp_init` is run. But since the logs are printed from BNM, I don't think this is needed.
Aslo that function needs to be ran before any of the `TryLoadBy`s.

> I just don't know if it does the hooks

From the error messages of methods not being found, do you have the correct Unity version selected in [GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L7)?

**Comment by EduModsS** [comment]
> > its right? doing this in main thread
> 
> Your `sleep` would block the main thread and stop the game from loading, so probably not.
> 
> > idk if i need to use AllowedLateInitHook or no
> 
> This needs to be used when the BNM loading happens after Unity's `il2cpp_init` is run. But since the logs are printed from BNM, I don't think this is needed. Aslo that function needs to be ran before any of the `TryLoadBy`s.
> 
> > I just don't know if it does the hooks
> 
> From the error messages of methods not being found, do you have the correct Unity version selected in [GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L7)?

I expressed myself badly, I'm not in the main thread, it's just the name of the thread lol, I don't know if I need allowed .. because I'm in the tryLoad, as soon as dlopen is triggered (1s delay), also the unity version of app i dont know, i trief any dumper it says it version 29 and then give error to dump

**Comment by YummyBacon5** [comment]
> the unity version of app i dont know, i tried any dumper and it says it version 29 and then give error to dump

You could try [AssetRipper](https://github.com/AssetRipper/AssetRipper) on the game to find out the version.

Also could you not use ` BNM::Loading::TryLoadByJNI`? Since BNM basically already does [internally](https://github.com/ByNameModding/BNM-Android/blob/master/src/Loading.cpp#L107) what you're trying to do now. And with this, you wouldn't need to call `AllowedLateInitHook`.

**Comment by BNM-Dev** [comment]
> Also could you not use ` BNM::Loading::TryLoadByJNI`? Since BNM basically already does [internally](https://github.com/ByNameModding/BNM-Android/blob/master/src/Loading.cpp#L107) what you're trying to do now. And with this, you wouldn't need to call `AllowedLateInitHook`.

Fully agree. 

And there is exists two other ways to get unity version:
1. Open libunity.so in hex editor and find it.
2. Call `get_unityVersion` (`BNM::GetExternMethod("UnityEngine.Application::get_unityVersion");`) and log it. `BNM::GetExternMethod` uses `il2cpp_resolve_icall` that will always work in any unity app, doesn't matter what is the version.

**Comment by Lsc0x80** [comment]
> > Also could you not use ` BNM::Loading::TryLoadByJNI`? Since BNM basically already does [internally](https://github.com/ByNameModding/BNM-Android/blob/master/src/Loading.cpp#L107) what you're trying to do now. And with this, you wouldn't need to call `AllowedLateInitHook`.
> 
> Fully agree.
> 
> And there is exists two other ways to get unity version:
> 
> 1. Open libunity.so in hex editor and find it.
> 2. Call `get_unityVersion` (`BNM::GetExternMethod("UnityEngine.Application::get_unityVersion");`) and log it. `BNM::GetExternMethod` uses `il2cpp_resolve_icall` that will always work in any unity app, doesn't matter what is the version.

also when starting the game, it writes the Unity version in the logs

**Comment by YummyBacon5** [comment]
Then do you have the correct line uncommented and the other lines commented?

It should be this one https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L18

**Comment by EduModsS** [comment]
ok, I managed to do it using TryLoadByJNI, and I discovered the version
