### ISSUE TITLE
I'm having some doubts about the performance aspects.

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#60]
Is the hook in BNM dynamically unhook? Does BNM support bytehook? If it is dynamically unhook, which performs better, bytehook or shadowhook? If bytehook performs better, how should I use bytehook as a hook?

**Comment by YummyBacon5** [comment]
There is an [unhook function](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L152), but this only works if your hooking software supports it.

And about which hook preforms better, then I'm not sure and that's not really a BNM question.

> how should I use bytehook as a hook?

You would edit the GlobalSettings.hpp file, in the [commented out code here](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L91), there's an example on how to use it. And if you chose ByteHook, then you would just edit the functions and enter what you use,

**Comment by BNM-Dev** [comment]
> And for about which hook preforms better: then I'm not sure. And that's not really a BNM question.

Yes, this is not BNM question. 

BNM performs very well, it tries use as less hooks as possible and don't perform a lot of calculations in them. I don't think that changing hooking software will somehow change performance. Any hooking software has some advantages and disadvantages, just use that one that you feel better with.

**Comment by 2079541547** [comment]
I apologize for my tone, but I can't help it. My English is not very good. However, does the UNHOOK of BNM need to be triggered manually? Perhaps it's worth considering dynamic UNHOOK, such as automatically performing UNHOOK if a certain function hasn't been called for several minutes and seconds.

**Comment by BNM-Dev** [comment]
UNHOOK used only for late init. If you don't know in which cases it should be used, just don't use it, forget about it.

**Comment by 2079541547** [comment]
I need too many HOOK functions, and I hope I can improve performance as much as possible by doing this

**Comment by BNM-Dev** [comment]
100 hooks empty hooks won't really affect performance. But one hook with a lot of calculation will affect very hard. Just write code that will not affect performance. 
UNHOOK can be used only in rare special cases or if you need hide hooks from detection.

**Comment by 2079541547** [comment]
Is rehooking after unhook directly called to load HOOK once

**Comment by BNM-Dev** [comment]
If you need hook method only once, you can use UNHOOK. 
```cpp
void *origin_or_hook_stub{};

void (*old_method)();
void new_method() {
    old_method();
    UNHOOK(origin_or_hook_stub);
    // Code ...
    // Or unhook here
    // UNHOOK(origin_or_hook_stub);
}

void Main() {
    void *addr = nullptr; 
    
    origin_or_hook_stub = HOOK(addr, new_method, old_method);
}
```

**Comment by 2079541547** [comment]
I want to realize how many seconds the judging function has not been called for automatically decoupling, but I need to repeat HOOK, but I don't know how to realize QWQ

**Comment by BNM-Dev** [comment]
You just wasting time, overthinking thing that not a problem. Unhooking things based on time is useless. Don't waste time on this. Count of hooks not a problem, problem is what inside them. You can have thousands of good written hooks and had good performance, but one bad hook can kill performance.

**Comment by 2079541547** [comment]
All right, then
