### ISSUE TITLE
How to use PLT series HOOK？

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#61]
I want to use bytehook as the HOOK because plt hook has lower performance overhead than inline hook after setting up

**Comment by BNM-Dev** [comment]
PLT can't be used for BNM. libunity imports il2cpp API using dlsym, so you can't use PLT. (As I understand how bytehook works, it will not replace this methods).

If you don't need ClassesManagement, you can disable it. It will reduce hooks to one hook. (il2cpp_init, but in next BNM version it will be unhooked after use).

And you can't use PLT hooks for hooking il2cpp game methods, because them not exported and can be called from lib itself.

**Comment by BNM-Dev** [comment]
And how many inline hooked methods you will have?

**Comment by 2079541547** [comment]
Probably around a few hundred, but there could be more

**Comment by BNM-Dev** [comment]
If them wrote normally, without hundreds of loops and other time consuming things this will not affect performance really hard. Only maybe lower on 1 - 5 fps. Still need do some checks, but for now, don't think about performance if project not done. Optimize it, only if you already has performance problems.

**Comment by 2079541547** [comment]
OK

**Comment by 2079541547** [comment]
![image](https://github.com/user-attachments/assets/e09c57a1-029d-4be8-97b1-91367026c497)
![image](https://github.com/user-attachments/assets/226f30f1-b398-4890-9e70-7f10c02db8ab)
My project will read the JSON file to obtain the configuration, and then load the SO file using functions such as loadAndInvoke IntFunctions and call the functions in it. It will be used in the HOOK function

**Comment by BNM-Dev** [comment]
You can use [yyjson](https://github.com/ibireme/yyjson) ([cpp wrapper](https://github.com/yosh-matsuda/cpp-yyjson)) to speed up json read. But I don't think that you will have jsons for megabytes.

Loading libs in game thread is bad idea. This is too time consuming. Try create other loading system.

**Comment by 2079541547** [comment]
This is the only way, because there is a problem with the sharing mode of shadowhook

**Comment by BNM-Dev** [comment]
In programming exist a lot of ways of doing something. Rational, irrational, doesn't matter just need try all, or figure out new one.
