### ISSUE TITLE
How to replicate this

### ISSUE THREAD

**Issue by Bandit00s** [ByNameModding/BNM-Android#65]
![image](https://github.com/user-attachments/assets/3553401d-1d5f-48c4-bacb-8ca85ad1c64c)
How would you replicate this `new OwnedVehicle {name = definition.name}` part with BNM? 

This is just an example, I'd like to know how to create a new class instance with fields initialized like this.

**Comment by BNM-Dev** [comment]
Even in C# fields got initialized after object created (you can see IL code to prove that). So just create it using `BNM::Class().CreateNewObjectParameters()`. And then using BNM::Field setup all fields that you need.

**Comment by ArifRios1st** [comment]
it should be like this if i'm not wrong

```cpp
Class OwnedVehicleCls = Class("","OwnedVehicle");
Field<String*> nameField = OwnedVehicleCls.GetField("name"); //or maybe Property


auto newOwnedVehicle = OwnedVehicleCls.CreateNewObjectParameters();
nameField[newOwnedVehicle].Set(CreateMonoString("New Vehicle"));
```

**Comment by Bandit00s** [comment]
> it should be like this if i'm not wrong
> 
> ```c++
> Class OwnedVehicleCls = Class("","OwnedVehicle");
> Field<String*> nameField = OwnedVehicleCls.GetField("name"); //or maybe Property
> 
> 
> auto newOwnedVehicle = OwnedVehicleCls.CreateNewObjectParameters();
> nameField[newOwnedVehicle].Set(CreateMonoString("New Vehicle"));
> ```

Thanks! I'll try this. 
I did my own setup based on what BNM dev said. But I got things mixed up. 
I created the object first, and then got the class and field from it or something. Also didn't use the Set method

**Comment by Bandit00s** [comment]
Ok this seems to be work. Doesn't behave exactly like the c# counterpart but it's probably related to other things I need to fix.
