### ISSUE TITLE
How to call unity to get Texture2d pointer function?

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#66]
I have some special needs, in my analysis I found that unity caches resources into memory and represents them as pointers, I need to get pointers to some specific Texture2d and redirect them, this should be a common solution for unity

**Comment by 2079541547** [comment]
How can I replace the original Texture2d and load images from storage

**Comment by BNM-Dev** [comment]
Use stbi_image and then using basic GLES api to create texture, create it in unity thread. Out from `glGenTextures` use as `nativeTex` when creating new `Texture2D`
