### ISSUE TITLE
Use the Internal:Load () function to crash.

### ISSUE THREAD

**Issue by TherCN** [ByNameModding/BNM-Android#68]
arch:arm64-v8a
android version:12
bnm version:latest(2.1.0)
hook libraries:have not
stacktrace:
![Screenshot_20240916_073507_bin mt plus](https://github.com/user-attachments/assets/bcfaede5-e4e2-4b79-84fc-47f946bc4e05)

cpp(jni) Code:
![Screenshot_20240916_073004_aidepro top](https://github.com/user-attachments/assets/4c8a5499-1ddf-47a3-9bec-78b5b08e1134)

C#Code :
```
using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class Player : MonoBehaviour
{
    void Start()
    {

    }
    void Update()
    {

    }
    private Config m_Config;

    public class Config
    {
        string Name;
        int Health;
        int Coins;
        public Config(string name, int health, int coins)
        {
            Name = name;
            Health = health;
            Coins = coins;
        }
        public int getHealth()
        {
            return Health; 
        }
   
    }
    public void OnButtonClick()
    {
        Debug.Log("onclick");
        if (Application.platform == RuntimePlatform.Android)
        {
            AndroidJavaClass clazz = new AndroidJavaClass("android.util.Log");
            clazz.CallStatic<Int32>("i", "TAG", "unitylog");
        }
        Config config = new("il2cpp", 100, 100);
        testPrivate(config);
        testPublic(config);
    }
    private void testPrivate(Config config)
    {
       Debug.Log("TestPrivate:OnInvoke");
    }
    public void testPublic(Config config)
    {
        Debug.Log("TestPublic:OnInvoke");
    }

}
```

**Comment by YummyBacon5** [comment]
You're in a com.example.application? Is this a Unity game?

**Comment by TherCN** [comment]
> You're in a com.example.application?
> 
> Is this a Unity game?

yes

**Comment by YummyBacon5** [comment]
Try moving `AddOnLoadedEvent` above `TryLoadByJNI`

**Comment by BNM-Dev** [comment]
You don't need to call `BNM::Internal::Load()`. It named INTERNAL, that means that it used only internally by BNM, or only if you know what are you doing. Just remove `BNM::Internal::Load()` call. You only need `TryLoadByJNI` and `AddOnLoadedEvent` calls.

**Comment by TherCN** [comment]
> You don't need to call `BNM::Internal::Load()`. It named INTERNAL, that means that it used only internally by BNM, or only if you know what are you doing. Just remove `BNM::Internal::Load()` call. You only need `TryLoadByJNI` and `AddOnLoadedEvent` calls.

That's what I did before. I didn't add Load(), Nor did it crash or execute the code in the function.

> Try moving `AddOnLoadedEvent` above `TryLoadByJNI`
Also, you do need to add hook libraries

I've done this before, but it didn't work.

**Comment by YummyBacon5** [comment]
Unless you have a class called `Player` with the defined fields, then this wouldn't work.

As those files are only an example, it [even says](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L114C8-L114C21) "let's imagine" that the class exists.

**Comment by TherCN** [comment]
> Unless you have a class called `Player` with the defined fields, then this wouldn't work.
> 
> As those files are only an example, it [even says](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L114) "let's imagine" that the class exists.

Thank you for your reply, it doesn't crash now, but when I want to use InvokeHook to Hook a method with data type parameters, for example:
`private void MoveToNextFloor(scrFloor floor, float exitAngle, HitMargin hitMargin)`
How should I modify the following cpp function parameter?
void invoked(UnityEngine::Object arg0, UnityEngine::Object arg1,float arg2,UnityEngine::Object arg3) {
    __android_log_print(3,"114514","Invoked");
}

**Comment by YummyBacon5** [comment]
Is `invoked` your hook?

If so, then what you have seems to be correct. But you'd need a `void* instance` parameter as the first parameter on there. And you'd also need an old function to call, if you want the original code to run.

**Comment by TherCN** [comment]
> Is `invoked` your hook?
> 
> If so, then what you have seems to be correct. But you'd need a `void* instance` parameter as the first parameter on there. And you'd also need an old function to call, if you want the original code to run.

Hook's new function doesn't work

**Comment by TherCN** [comment]
> > Is `invoked` your hook?
> > If so, then what you have seems to be correct. But you'd need a `void* instance` parameter as the first parameter on there. And you'd also need an old function to call, if you want the original code to run.

The new function (invoked) of the hook does not work.

**Comment by YummyBacon5** [comment]
Try using normal `HOOK` instead. As these different hook functions do different things. As [described here](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L147-L150).

**Comment by TherCN** [comment]
> Try using normal `HOOK` instead. As these different hook functions do different things. As [described here](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L147-L150).

The new function (invoked) of the hook was only executed once, and then it was not executed again.
Do you have a discord communication server? Can I join in?

**Comment by zy1p** [comment]
> > Try using normal `HOOK` instead. As these different hook functions do different things. As [described here](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L147-L150).
> 
> The new function (invoked) of the hook was only executed once, and then it was not executed again. Do you have a discord communication server? Can I join in?

It relates to shadowhook, use unique mode to initialise shadowhook should solve this problem.

**Comment by TherCN** [comment]
> > > Try using normal `HOOK` instead. As these different hook functions do different things. As [described here](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L147-L150).
> > 
> > 
> > The new function (invoked) of the hook was only executed once, and then it was not executed again. Do you have a discord communication server? Can I join in?
> 
> It relates to shadowhook, use unique mode to initialise shadowhook should solve this problem.

Sorry, please forgive me for continuing to ask for help in this problem.
C# code is as follows. I want to get the value of Coins field in newConfig. How can I write hook function and print it?
```
public class Config
    {
        string Name;
        int Health;
        public double Coins;
        public Config newConfig;
        public Config(string name, int health, int coins)
        {
            Name = name;
            Health = health;
            Coins = coins;
            
        }
        public int getHealth()
        {
            return Health; 
        }
        public void initConfig()
        {
            newConfig = new("Name", 200, 200);
        }
}
```
```
using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public partial class Player : MonoBehaviour
{
    void Start()
    {

    }
    void Update()
    {

    }
    private Config m_Config;
    public void OnButtonClick()
    {
       
        if (Application.platform == RuntimePlatform.Android)
        {
            AndroidJavaClass clazz = new AndroidJavaClass("android.util.Log");
            clazz.CallStatic<Int32>("i", "TAG", "OnClick");
        }
        Config config = new("il2cpp", 100, 100);
        config.initConfig();
        testPrivate(config);
        testPublic(config);
    }
    private void testPrivate(Config config)
    {
        Debug.Log(String.Format("Coins:{0:F},new Coins:{1:F}",config.Coins,config.newConfig.Coins));
        Debug.Log("TestPrivate:OnInvoke");
    }
}
```
I tried to write it like this, but I got the new Coins field value of 0.
```
void PlayerUpdate(BNM::UnityEngine::Object *instance,BNM::UnityEngine::Object *config) {
    old_PlayerUpdate(instance,config); // Call original code
	__android_log_print(6, BNM_TAG, "BNM:Update");
    // Checking whether the pointer to the m_Config field data is correct
    auto PlayerConfigClass = BNM::Class("",OBFUSCATE_BNM("Config"));
	BNM::Field<double> Coins = PlayerConfigClass.GetField("Coins");
	double coin = Coins[config].Get();
	BNM::Field<BNM::UnityEngine::Object> newConfig = PlayerConfigClass.GetField("newConfig");
	auto newCoins = Coins[newConfig[config].GetPointer()].Get();
	__android_log_print(6,BNM_TAG,"coins:%f,new Coins:%f",coin,newCoins);
}
```

**Comment by YummyBacon5** [comment]
```cpp
BNM::Field<BNM::UnityEngine::Object *> m_Config;
BNM::Field<double> configCoins;

void PlayerUpdate(BNM::UnityEngine::Object *instance) {
    old_PlayerUpdate(instance);
    
    auto coins = configCoins[m_Config[instance]];
    double newCoins = 100;
    
    BNM_LOG_INFO(OBFUSCATE_BNM("Current coins: %d, New coins: %d"), coins, newCoins);
    coins.Set(newCoins);
}

void OnLoaded() {
    m_Config = BNM::Class(OBFUSCATE_BNM("Player")).GetField(OBFUSCATE_BNM("m_Config"));
    configCoins = BNM::Class(OBFUSCATE_BNM("Config")).GetField(OBFUSCATE_BNM("Coins"));
}
```

Something along the lines of this should work.

Also, I recommended that you try to solve these issues yourself and try to understand the code? Maybe try looking at the example files more

**Comment by TherCN** [comment]
> ```c++
> BNM::Field<BNM::UnityEngine::Object *> m_Config;
> BNM::Field<double> configCoins;
> 
> void PlayerUpdate(BNM::UnityEngine::Object *instance) {
>     old_PlayerUpdate(instance);
>     
>     auto coins = configCoins[m_Config[instance]];
>     double newCoins = 100;
>     
>     BNM_LOG_INFO(OBFUSCATE_BNM("Current coins: %d, New coins: %d"), coins, newCoins);
>     coins.Set(newCoins);
> }
> 
> void OnLoaded() {
>     m_Config = BNM::Class(OBFUSCATE_BNM("Player")).GetField(OBFUSCATE_BNM("m_Config"));
>     configCoins = BNM::Class(OBFUSCATE_BNM("Config")).GetField(OBFUSCATE_BNM("Coins"));
> }
> ```
> 
> 类似这样的方法应该可以工作。（我还没有测试过）
> 
> 另外，我建议你尝试自己解决这些问题并尝试理解代码？也许尝试多看看示例文件

Thank you! The problem has been solved, I will close this issue.
