### ISSUE TITLE
Can BNM be used in Xposed, Lspose, and Lspatch modules?

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#69]
I want to hook the game in the module, but I have a question: How does BNM obtain the offset? How should I change from/doc/maps to the specified program's/doc/maps? I think obtaining the offset is enough

**Comment by YummyBacon5** [comment]
You could read the program's source code to find out.

But basically, it finds the where Unity's IL2CPP API methods are, and it then calls them.
It also uses IL2CPP header files to access data.

I'm also not sure what you mean by "from/doc/maps" and "program's/doc/maps".

**Comment by BNM-Dev** [comment]
You can just load library into target game form module and this will work like adding lib to apk itself.
