### ISSUE TITLE
Hooking question 

### ISSUE THREAD

**Issue by ADH36** [ByNameModding/BNM-Android#7]
First of all sorry for noob question but i need help . 

namespace  Legion.Shared.Battles.Data.Stats
{

	public class AbilityStats : StatsBase<AbilityStats>
	{
		
		public float HealingRadius
		{
		
			get
			{
				return 0f;
			}
		}

Imagine this is a game code , and i want to hook HealingRadius or say get_HealingRadius . 

How would i do that ? i have tried multiple work arounds like - 

auto Player = LoadClass("Legion.Shared.Model","AbilityStats");
HOOK(Player.GetMethodByName("get_Cooldown", 0.0).GetOffset(), get_CD, old_CD);

dll name - Legion.Shared.Model.dll

Help will be thankful .

**Comment by chiteroman** [comment]
```cpp
LoadClass AbilityStats("Legion.Shared.Battles.Data.Stats", "AbilityStats");
auto HealingRadius = AbilityStats.GetPropertyByName("HealingRadius").getter.GetOffset();
HOOK(HealingRadius, my_custom_method, original_method);
```

**Comment by ADH36** [comment]
No , it's not working with above solution as well .

**Comment by BNM-Dev** [comment]
> No , it's not working with above solution as well .

It work with offsets?

**Comment by ADH36** [comment]
> 

Yup same source code , only change is offsets and yes it works with offsets .

**Comment by BNM-Dev** [comment]
> > 
> 
> Yup same source code , only change is offsets and yes it works with offsets .

Need see, because for me and a lot of other people BNM work without any problems.
