### ISSUE TITLE
HOOK fail

### ISSUE THREAD

**Issue by lanboone** [ByNameModding/BNM-Android#70]
`
![1726642596445](https://github.com/user-attachments/assets/6d994f8e-0d50-4bdf-86f6-bef7b103c637)
![1726642671613](https://github.com/user-attachments/assets/2c0e94df-fc7f-4ea1-a21f-810c1edb128d)
Why do my hookstart and update methods work, but other methods of this class hook up

**Comment by YummyBacon5** [comment]
`InvokeHook` is meant for methods that are called directly from Unity.

You should use normal `HOOK` instead for the `ClickQueHuan` method.

In the [example file](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L147-L150), it also describes what each of these hooks do.

**Comment by TherCN** [comment]
我需要更多的jni代码上下文以便诊断问题

**Comment by YummyBacon5** [comment]
> I need more context of the jni code in order to diagnose the problem

@TherCN, JNI code is irrelevant here as the original poster didn't send any? Plus what I said should be able to fix the problem

> 我需要更多的jni代码上下文以便诊断问题

@TherCN，JNI 代码在这里无关紧要，因为原始海报没有发送任何代码？再加上我说的应该可以解决问题

**Comment by lanboone** [comment]
> `InvokeHook` is meant for methods that are called directly from Unity.
> 
> You should use normal `HOOK` instead for the `ClickQueHuan` method.
> 
> In the [example file](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L147-L150), it also describes what each of these hooks do.

Thank you for your answer, but it still doesn't solve the problem. Is that right?``

`void (*old_PlayerClickQueHuan)(BNM::UnityEngine::Object *);
void PlayerClickQueHuan(BNM::UnityEngine::Object *instance) {
    BNM_LOG_ERR("CCCCCCCCCCCCPlayerClickQueHuanCCCCCCCCCCCCCCCCCCCCCCC");

}


void (*old_PlayerStart)(BNM::UnityEngine::Object *);
void PlayerStart(BNM::UnityEngine::Object *instance) {
//    old_PlayerStart(instance); // Call original code
    BNM_LOG_ERR("old_PlayerStart");
}


// Here you can get all the necessary information
void OnLoaded_Example_01() {
    using namespace BNM; // To avoid writing BNM:: in this method
    BNM_LOG_ERR("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");

    // Get the UnityEngine class.Object
    ObjectClass = Class(OBFUSCATE_BNM("UnityEngine"), OBFUSCATE_BNM("Object"));
    // Get UnityEngine.Object::ToString method with 0 parameters
    ObjectToString = ObjectClass.GetMethod(OBFUSCATE_BNM("ToString"), 0);
    // Get UnityEngine.Object::name property
    ObjectName = ObjectClass.GetProperty(OBFUSCATE_BNM("name"));

    auto ButtonHandler = Class(OBFUSCATE_BNM(""), OBFUSCATE_BNM("ButtonHandler"));

    auto ClickQueHuan = ButtonHandler.GetMethod(OBFUSCATE_BNM("ClickQueHuan"));
    HOOK (ClickQueHuan, PlayerClickQueHuan, old_PlayerClickQueHuan);
    BNM_LOG_ERR("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");


//    auto Start = ButtonHandler.GetMethod(OBFUSCATE_BNM("Start"));
//    InvokeHook(Start, PlayerStart, old_PlayerStart);



}`

**Comment by lanboone** [comment]
> `InvokeHook` is meant for methods that are called directly from Unity.
> 
> You should use normal `HOOK` instead for the `ClickQueHuan` method.
> 
> In the [example file](https://github.com/ByNameModding/BNM-Android/blob/master/examples/01_Basics.cpp#L147-L150), it also describes what each of these hooks do.

Thank you for your answer, but it still doesn't solve the problem. Is that right?

**> void (*old_PlayerClickQueHuan)(BNM::UnityEngine::Object *);
void PlayerClickQueHuan(BNM::UnityEngine::Object *instance) {
    BNM_LOG_ERR("CCCCCCCCCCCCPlayerClickQueHuanCCCCCCCCCCCCCCCCCCCCCCC");

}

void (*old_PlayerStart)(BNM::UnityEngine::Object *);
void PlayerStart(BNM::UnityEngine::Object *instance) {
//    old_PlayerStart(instance); // Call original code
    BNM_LOG_ERR("old_PlayerStart");
}

void OnLoaded_Example_01() {
    using namespace BNM; // To avoid writing BNM:: in this method
    BNM_LOG_ERR("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");

    ObjectClass = Class(OBFUSCATE_BNM("UnityEngine"), OBFUSCATE_BNM("Object"));
    ObjectToString = ObjectClass.GetMethod(OBFUSCATE_BNM("ToString"), 0);
    ObjectName = ObjectClass.GetProperty(OBFUSCATE_BNM("name"));

    auto ButtonHandler = Class(OBFUSCATE_BNM(""), OBFUSCATE_BNM("ButtonHandler"));

    auto ClickQueHuan = ButtonHandler.GetMethod(OBFUSCATE_BNM("ClickQueHuan"));
    HOOK (ClickQueHuan, PlayerClickQueHuan, old_PlayerClickQueHuan);
    BNM_LOG_ERR("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");


//    auto Start = ButtonHandler.GetMethod(OBFUSCATE_BNM("Start"));
//    InvokeHook(Start, PlayerStart, old_PlayerStart);

}**

**Comment by YummyBacon5** [comment]
Please learn how to format your code so it can be read better. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

Do you have your hooking software added into [GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L91)?

**Comment by lanboone** [comment]
> Please learn how to format your code so it can be read better. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> 
> Do you have your hooking software added into [GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L91)?

thank you for your suggestion！
I have introduced GlobalSettings

**Comment by lanboone** [comment]
> Please learn how to format your code so it can be read better. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> 
> Do you have your hooking software added into [GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L91)?

thank you for your suggestion！
I have introduced GlobalSettings

**Comment by lanboone** [comment]
> Please learn how to format your code so it can be read better. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> 
> Do you have your hooking software added into [GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp#L91)?

thank you for your suggestion！
I have introduced GlobalSettings
```ruby
#include <BNM/UserSettings/GlobalSettings.hpp>

#include <BNM/Class.hpp>
#include <BNM/Field.hpp>
#include <BNM/Method.hpp>
#include <BNM/Property.hpp>
#include <BNM/Operators.hpp>
#include <BNM/BasicMonoStructures.hpp>

#include <iostream>


// Used to not write BNM::Structures for each type
using namespace BNM::Structures; // Mono::String, Mono::Array etc.
using namespace BNM::Operators; // Operators for methods, fields, and properties

// Variable for storing class
BNM::Class ObjectClass{};
// Variable for storing property
BNM::Property<Mono::String *> ObjectName{};
// Variable for storing method
BNM::Method<Mono::String *> ObjectToString{};
BNM::Method<int> NewResetFlag{};
// Variable for storing field
BNM::Field<void *> PlayerConfig{};
BNM::Field<Mono::String *> ConfigName{};
BNM::Field<int> ConfigHealth{};
BNM::Field<int> ConfigCoins{};

// Variable for storing pointer to field
int *PlayerConfigPtr = nullptr;
BNM::UnityEngine::Object *Player = nullptr;

#include <jni.h>
#include <string>
jobject obj1;
JNIEnv* env1;
extern "C" JNIEXPORT jstring JNICALL
Java_com_android_boot_MainActivity_stringFromJNI(
        JNIEnv* env,
        jobject obj) {
    std::string hello = "Hello from C++";
    obj1 = obj;
    env1 = env;

    jclass clazz = env1->GetObjectClass(obj1);
    jmethodID methodID = env1->GetMethodID(clazz, "commandReceived", "(Ljava/lang/String;)V");
    if (methodID != nullptr) {
        jstring command = env1->NewStringUTF("Hello from native");
        env1->CallVoidMethod(obj1, methodID, command);
        env1->DeleteLocalRef(command);
    }


    return env->NewStringUTF(hello.c_str());
}


void (*old_PlayerClickQueHuan)(BNM::UnityEngine::Object *);
void PlayerClickQueHuan(BNM::UnityEngine::Object *instance) {
    BNM_LOG_ERR("CCCCCCCCCCCCPlayerClickQueHuanCCCCCCCCCCCCCCCCCCCCCCC");

}

void (*old_PlayerStart)(BNM::UnityEngine::Object *);
void PlayerStart(BNM::UnityEngine::Object *instance) {
//    old_PlayerStart(instance); // Call original code
    BNM_LOG_ERR("old_PlayerStart");
}

void OnLoaded_Example_01() {
    using namespace BNM; // To avoid writing BNM:: in this method
    BNM_LOG_ERR("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");

    ObjectClass = Class(OBFUSCATE_BNM("UnityEngine"), OBFUSCATE_BNM("Object"));
    ObjectToString = ObjectClass.GetMethod(OBFUSCATE_BNM("ToString"), 0);
    ObjectName = ObjectClass.GetProperty(OBFUSCATE_BNM("name"));

    auto ButtonHandler = Class(OBFUSCATE_BNM(""), OBFUSCATE_BNM("ButtonHandler"));

    auto ClickQueHuan = ButtonHandler.GetMethod(OBFUSCATE_BNM("ClickQueHuan"));
    HOOK (ClickQueHuan._data->methodPointer, PlayerClickQueHuan, old_PlayerClickQueHuan);
    BNM_LOG_ERR("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");


//    auto Start = ButtonHandler.GetMethod(OBFUSCATE_BNM("Start"));
//    InvokeHook(Start, PlayerStart, old_PlayerStart);

}
```

**Comment by YummyBacon5** [comment]
Do your logs inside `OnLoaded_Example_01` get logged at all?
If not, then you haven't BNM correctly.

And have you edited the `GlobalSettings.hpp` file to include your hooking software?

**Comment by YummyBacon5** [comment]
If you used `InvokeHook` to hook Start. Then it would work, as this doesn't use your hooking software, and instead BNM changes stuff itself.

What hooking software are you using? If not any, then you need to add one into `GlobalSettings.hpp`.

**Comment by lanboone** [comment]
> If you used `InvokeHook` to hook Start. Then it would work, as this doesn't use your hooking software, and instead BNM changes stuff itself.
> 
> What hooking software are you using? If not any, then you need to add one into `GlobalSettings.hpp`.
> 
> Also are there any errors from BNM? Like can the method not be found, etc? And try including a parameter count where you call `GetMethod`.
Thank you！ I understand what you mean

**Comment by YummyBacon5** [comment]
> Thank you！ I understand what you mean

So does it work?
