### ISSUE TITLE
Error calling ToString function

### ISSUE THREAD

**Issue by 2079541547** [ByNameModding/BNM-Android#74]
![image](https://github.com/user-attachments/assets/28ecdb2b-d8ce-4123-ab60-30f96176b1be)
![image](https://github.com/user-attachments/assets/38bba16d-c070-4cab-b29c-193443c08680)

I found that not only calling this function, but even some of the basic BNM functions don't work, such as setting the value of the array

**Comment by YummyBacon5** [comment]
I'm not sure if there's enough information here to help you?

But are there any errors or warnings logged from BNM when you run it?
And have you added the hooking software and selected the correct Unity version in `[GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp)`?

**Comment by 2079541547** [comment]
![image](https://github.com/user-attachments/assets/d3a05e6c-78b5-40c3-8d21-f5dacaec5e84)
I don't think that's the problem.

**Comment by zy1p** [comment]
have you added the hooking software in GlobalSettings.hpp?

**Comment by 2079541547** [comment]
![image](https://github.com/user-attachments/assets/da8f1720-db05-4ebc-a898-6d66c5ccd51f)
without doubt

**Comment by zy1p** [comment]
have you Initialized it?

**Comment by 2079541547** [comment]
![image](https://github.com/user-attachments/assets/84cc67cd-34b7-4936-a584-5adbb49146b4)
has been initialised, and although the code is a bit abstract, there is no problem testing the Hook functionality so far!

**Comment by BNM-Dev** [comment]
Can you provide full crash log?

**Comment by 2079541547** [comment]
[vivo-V2166A-Android-12_2024-10-25_212433.log](https://github.com/user-attachments/files/17522737/vivo-V2166A-Android-12_2024-10-25_212433.log)
If source code is required
https://github.com/2079541547/TEFModLoader/blob/main/core/src/main/cpp/TEFModLoader/src/TEFModLoader.cpp

**Comment by 2079541547** [comment]
Is it because of the shaodwhook error, so can I get the instance manually?

**Comment by BNM-Dev** [comment]
I don't know exactly what is going wrong (not enough information), so try to do sth, like add more logs to see if all found, hooked correctly.

**Comment by 2079541547** [comment]
哥们有实力啊，解决了
