### ISSUE TITLE
help!some method hook fail

### ISSUE THREAD

**Issue by dw317748627** [ByNameModding/BNM-Android#75]
How do I hook methods that have action parameters?

![screenshot-20241021-103505](https://github.com/user-attachments/assets/d5a49c4e-80b3-4212-9fbf-38aab4895126)
![screenshot-20241021-103518](https://github.com/user-attachments/assets/7cac816a-6296-41fb-8ce4-cccde415a869)
![screenshot-20241021-103533](https://github.com/user-attachments/assets/6f81b107-6842-41d9-92aa-63aca3837bb7)

**Comment by dw317748627** [comment]
![image](https://github.com/user-attachments/assets/2f1f6999-8b10-4868-83dc-743a01e6608f)

**Comment by dw317748627** [comment]
[17.zip](https://github.com/user-attachments/files/17454964/17.zip)

**Comment by YummyBacon5** [comment]
Try using `BNM::UnityEngine::UnityAction` instead?
Although, I'm not too sure as I haven't used Actions.

**Comment by BNM-Dev** [comment]
![изображение](https://github.com/user-attachments/assets/7aa8266a-c7c5-4c0f-8d16-2a422c71199b)
You do not calling `DoAction3` in code.
