### ISSUE TITLE
Crash When Using Unity Version 6000 Due to Missing API Header in BNM

### ISSUE THREAD

**Issue by solomode0001** [ByNameModding/BNM-Android#76]
Some games are using Unity version 6000, but on BNM there’s no API header for Unity version 6000. So, I tried using #define UNITY_VER 232 // 2023.2.x+ instead, but the game ended up crashing.

Any ideas on how to fix this?

Log:
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '6000.0.23f1 (1c4764c07fb4)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a', Stripping 'Disabled'
Build fingerprint: 'google/google/G011A:9/mv-dev103041042:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2024-10-24 18:28:01.232472116+0700
pid: 5253, tid: 5253, name: .stickwarlegacy  >>> com.maxgames.stickwarlegacy <<<
uid: 10076
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr --------
    r0  00d2d8a6  r1  09dc710c  r2  a842a7bc  r3  00000038
    r4  c8fc358c  r5  09dc6f40  r6  00000000  r7  09dc6f40
    r8  00000000  r9  bd60683a  r10 c8fc358c  r11 c8fc3628
    ip  09cd4294  sp  c8fc3528  lr  07afe214  pc  07aff128

backtrace:
      #00 pc 00aa7128  /data/app/com.maxgames.stickwarlegacy-nlbtb40wmHEt_pcAsGu-vw==/lib/arm/libil2cpp.so (BuildId: 890c4b492e963cce861ffd26dea64f9a56e71a90)
      #01 pc 0006983c  /data/app/com.maxgames.stickwarlegacy-nlbtb40wmHEt_pcAsGu-vw==/lib/arm/libBNM.so (BuildId: 89468e308850b84531e7ab5643ec00b5dbb54118)
```

**Comment by BNM-Dev** [comment]
This is strange, because there are no difference between 2023.2.0 headers and 6000.0.24 headers.
![изображение](https://github.com/user-attachments/assets/dc0a4a31-3013-4055-aa37-b755bd08b833)

How I see, `libil2cpp.so` trying to use invalid pointer. And it was called from `libBNM.so`. But that's all that I can say about this crash log.

**Comment by solomode0001** [comment]
You're right! 😅 After checking again, the crash error is in my own code, not BNM's. 🙈 Sorry about that! 🙏 And you were spot on 🎯—API 2023.2.x+ is fully compatible with Unity 6000. 🚀🎉
