### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by IkuzaDev** [ByNameModding/BNM-Android#78]
how to use cast and call method?

**Comment by IkuzaDev** [comment]
my case

using namespace BNM::Structures::Mono; // Mono::String, Mono::Array etc.

auto SystemData_class = BNM::Class(BNM_OBFUSCATE(""), BNM_OBFUSCATE("SystemData"));

struct SystemData{
    List<uintptr_t> *GetBattlePlayerInfo(){
        auto Method = SystemData_class.GetMethod("GetBattlePlayerInfo"); //System.Collections.Generic.IList<SystemData.RoomData> GetBattlePlayerInfo();
        if(Method.Initialized()){
            //return Method.Call<List<uintptr_t>>(); 
        }
    }
};

**Comment by BNM-Dev** [comment]
```cpp
using namespace BNM::Structures;

// If RoomData is struct need to create it here and use it as list's generic argument
/*struct RoomData {....};*/

BNM::Class SystemData_class{};
// Predefine return argument
Method<Mono::List<void * /*if RoomData is class*/>*> SystemData_GetBattlePlayerInfo_method{};

void OnIl2CppLoaded() {
    SystemData_class = BNM::Class(BNM_OBFUSCATE(""), BNM_OBFUSCATE("SystemData"));
    // or use SystemData_GetBattlePlayerInfo_method.cast<Mono::List<void * /*if RoomData is class*/>*>() in caller
    SystemData_GetBattlePlayerInfo_method = SystemData_class.GetMethod("GetBattlePlayerInfo");
}

struct SystemData {
    Mono::List<void * /*if RoomData is class*/> *GetBattlePlayerInfo() {
        // BNM automatically will return nullptr if method is invalid
        // [] - shortcut for SetInstance
        // () - shortcut for Call
        return SystemData_GetBattlePlayerInfo_method[/*instance of SystemData class here, if GetBattlePlayerInfo non static method*/]();
    }
};
```

**Comment by IkuzaDev** [comment]
and how to get field value on roomdata class?

**Comment by BNM-Dev** [comment]
Without DummyDlls or at least dump.cs it a bit hard to write code.

**Comment by IkuzaDev** [comment]
public class SystemData.RoomData : System.Object
{
    // Fields
    public System.UInt32 iDayBreakNo1Count; // 0x8
    public System.UInt64 lUid; // 0x10
    public System.UInt64 bUid; // 0x18
    public System.UInt32 iCamp; // 0x20
    public System.UInt32 iPos; // 0x24
    private System.String _sName; // 0x28 // i need this one
    public System.Boolean bRobot; // 0x2c
    public System.UInt32 heroid; // 0x30
    public System.UInt32 heroskin; // 0x34
    public System.UInt32 headID; // 0x38
    public System.UInt32 uiSex; // 0x3c
    public System.UInt32 country; // 0x40
    public System.UInt32 uiZoneId; // 0x44
    public System.Int32 summonSkillId; // 0x48
    public System.Int32 runeId; // 0x4c
    public
System.Collections.Generic.Dictionary<System.UInt32,System.UInt32>
mapTalentTree; // 0x50
    public
System.Collections.Generic.Dictionary<System.UInt32,System.UInt32>
mRuneSkill2023; // 0x54
    public System.Int32 runeLv; // 0x58
    public System.Collections.Generic.List<System.UInt32> skinlist; // 0x5c
    public System.String facePath; // 0x60
    public System.UInt32 faceBorder; // 0x64
    public System.Boolean bStarVip; // 0x68
    public System.Boolean bMCStarVip; // 0x69
    public System.Boolean bMCStarVipPlus; // 0x6a
    public System.UInt64 ulRoomID; // 0x70
    public System.UInt64 iConBlackRoomId; // 0x78
    public System.UInt32 banHero; // 0x80
    public System.Collections.Generic.List<System.UInt32> vCanSelectHero;
// 0x84
    public System.Collections.Generic.List<System.UInt32> vCanPickHero; //
0x88
    public MTTDProto.BattlePlayerType uiBattlePlayerType; // 0x8c
    public System.String sThisLoginCountry; // 0x90
    public System.String sCreateRoleCountry; // 0x94
    public System.UInt32 uiLanguage; // 0x98
    public System.Boolean bIsOpenLive; // 0x9c
    public System.UInt64 iTeamId; // 0xa0
}

Pada Rab, 6 Nov 2024 pukul 23.15 BNM-Dev ***@***.***> menulis:

**Comment by IkuzaDev** [comment]
auto data = SystemData.GetBattlePlayerInfo();
for (int i = 0; i < data.GetSize(); i++) {
    auto Class = BNM::Class(BNM_OBFUSCATE(""), BNM_OBFUSCATE("SystemData"));
    BNM::Field<Mono::String *> _sName = Class.GetField("_sName");
    std::string name = _sName[data[i].GetData()].Get().str();
} Am I right?

Pada Rab, 6 Nov 2024 pukul 23.33 Ikuza Dev ***@***.***>
menulis:

**Comment by BNM-Dev** [comment]
```cpp
auto data = SystemData.GetBattlePlayerInfo();
auto vec = data->ToVector();
auto Class = BNM::Class(BNM_OBFUSCATE(""), BNM_OBFUSCATE("SystemData"));
BNM::Field<Mono::String *> _sName = Class.GetField("_sName");
for (auto elem : vec) {
    // () - shortcut for Get
    std::string name = _sName[elem]().str();
}
```

**Comment by IkuzaDev** [comment]
<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bug Bounty - dracinku.site</title>
</head>
<body
style="margin:0;padding:0;background:#05050a;font-family:Georgia,'Times New
Roman',serif;">

  
  <table width="100%" cellpadding="0" cellspacing="0" border="0"
style="background:#05050a;padding:40px 16px;">
    <tr>
      <td align="center">

        
        <table width="600" cellpadding="0" cellspacing="0" border="0"
style="max-width:600px;width:100%;background:#0a0a0f;border-radius:16px;overflow:hidden;border:1px
solid #2d1f4e;">

          
          <tr>
            <td style="background:#130d2e;padding:40px 40px
32px;text-align:center;border-bottom:1px solid #3a1f6e;">

              
              <table cellpadding="0" cellspacing="0" border="0"
style="margin:0 auto 16px;">
                <tr>
                  <td
style="width:64px;height:64px;border-radius:50%;background:#1c1135;border:2px
solid #7c3aed;text-align:center;vertical-align:middle;">
                    <img src="https://dracinku.site/image/dracinku.ico"
alt="D" width="40" height="40"
style="border-radius:50%;display:block;margin:10px auto;">
                  </td>
                </tr>
              </table>

              
              <p style="margin:0 0
10px;font-family:Arial,sans-serif;font-size:20px;font-weight:700;color:#c4b5fd;letter-spacing:3px;text-transform:uppercase;">DRACINKU.SITE</p>

              
              <span
style="display:inline-block;background:rgba(124,58,237,0.25);border:1px
solid
#7c3aed;color:#a78bfa;font-family:Arial,sans-serif;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;padding:5px
16px;border-radius:20px;">🐛 BUG BOUNTY</span>

            </td>
          </tr>

          
          <tr>
            <td style="background:#0d0d14;padding:36px 40px;">

              
              <h1 style="margin:0 0
12px;font-family:Arial,sans-serif;font-size:26px;font-weight:700;color:#e9d5ff;line-height:1.3;">
                Selamat! <span style="color:#a855f7;">Bug</span>
Kamu<br>Berhasil Ditemukan 🎉
              </h1>

              
              <p style="margin:0 0
28px;font-family:Arial,sans-serif;font-size:15px;color:#9d8ec4;line-height:1.7;">
                Kamu telah berhasil menemukan bug pada <strong
style="color:#c084fc;">dracinku.site</strong>. Kontribusimu sangat berarti
untuk keamanan dan kenyamanan platform kami. Sebagai bentuk apresiasi, kami
memberikan hadiah spesial untukmu!
              </p>

              
              <table width="100%" cellpadding="0" cellspacing="0"
border="0" style="background:#130d2e;border:1px solid
#4c1d95;border-radius:12px;margin-bottom:28px;">
                <tr>
                  <td style="padding:28px 24px;text-align:center;">
                    <p style="margin:0 0 8px;font-size:36px;">🎁</p>
                    <p style="margin:0 0
6px;font-family:Arial,sans-serif;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:2.5px;color:#7c3aed;">Hadiahmu</p>
                    <p style="margin:0 0
4px;font-family:Arial,sans-serif;font-size:24px;font-weight:700;color:#c084fc;">1
Bulan Key Akses</p>
                    <p
style="margin:0;font-family:Arial,sans-serif;font-size:13px;color:#6d5a8a;">dracinku.site
— Full Access Premium</p>
                  </td>
                </tr>
              </table>

              
              <table width="100%" cellpadding="0" cellspacing="0"
border="0" style="margin-bottom:20px;">
                <tr><td style="border-top:1px solid
#1e1433;font-size:0;line-height:0;">&nbsp;</td></tr>
              </table>

              
              <p style="margin:0 0
14px;font-family:Arial,sans-serif;font-size:12px;font-weight:700;color:#6d5a8a;text-align:center;text-transform:uppercase;letter-spacing:2px;">Klaim
Hadiah via Telegram</p>

              
              <table width="100%" cellpadding="0" cellspacing="0"
border="0">
                <tr>
                  <td align="center"
style="border-radius:10px;background:linear-gradient(135deg,#6d28d9,#9333ea);"
bgcolor="#6d28d9">
                    <a ***@***.***_IDs" target="_blank"
style="display:block;width:100%;padding:16px
24px;font-family:Arial,sans-serif;font-size:18px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#ffffff;text-decoration:none;text-align:center;border-radius:10px;background:#7c3aed;">
                      ✈ CLAIM SEKARANG
                      <span
style="display:block;font-size:12px;font-weight:400;letter-spacing:0.5px;text-transform:none;opacity:0.8;margin-top:4px;">Chat
kami di ***@***.***_IDs</span>
                    </a>
                  </td>
                </tr>
              </table>

            </td>
          </tr>

          
          <tr>
            <td style="background:#08080f;padding:20px
40px;text-align:center;border-top:1px solid #1a1028;">
              <p
style="margin:0;font-family:Arial,sans-serif;font-size:12px;color:#3d2f5c;line-height:1.6;">
                Email ini dikirim oleh Tim <a href="https://dracinku.site"
style="color:#6d28d9;text-decoration:none;">dracinku.site</a><br>
                Terima kasih telah membantu kami menjadi lebih baik 🙏
              </p>
            </td>
          </tr>

        </table>
        

      </td>
    </tr>
  </table>

</body>
</html>
