### ISSUE TITLE
enum parameter

### ISSUE THREAD

**Issue by Darklaser38** [ByNameModding/BNM-Android#79]
Hello i have a problem. I'm trying to hook 2 functions. But they have the same name and parameter name. So i tried adding the parameter type but i don't know how to do that for the enum type function :

public static bool IsShallot(CharacterInfo.ID charaId)
{
	return default(bool);
}

public static bool IsShallot(int charaId)
{
	return default(bool);
}

Hope i didn't forget anythings that can help

**Comment by BNM-Dev** [comment]
Find enum as any other class and use that class as parameter type.

**Comment by Darklaser38** [comment]
It worked thx idk why i didn't though about doing that my issue is solved.
