### ISSUE TITLE
 How to get the object

### ISSUE THREAD

**Issue by 1SUUU2** [ByNameModding/BNM-Android#80]
```
// BobMainScript.dll
[Serializable]
public class usercmd.SettingAttr : System.Object, ProtoBuf.IExtensible
	// Fields
	private System.String _Name;
	private System.UInt32 _SchId;
	private System.UInt32 _IsSel;
	private readonly System.Collections.Generic.List<usercmd.SettingAttr.Attr> _AttrList;
	private readonly System.Collections.Generic.List<usercmd.SettingAttr.ModelAttr> _ModelAttrList;
	private ProtoBuf.IExtension extensionObject;

	// Methods
	public System.Void .ctor(); 
	public System.String get_Name(); 
	public System.Void set_Name(System.String value); 
	public System.UInt32 get_SchId(); 
	public System.Void set_SchId(System.UInt32 value);
	public System.UInt32 get_IsSel(); 
	public System.Void setsettingAttrInstance _IsSel(System.UInt32 value); 
	public System.Collections.Generic.List<usercmd.SettingAttr.Attr> get_AttrList(); 
	public System.Collections.Generic.List<usercmd.SettingAttr.ModelAttr> get_ModelAttrList(); 
	private ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(System.Boolean createIfMissing);
	public System.String get_name(); 

}
```

'm modifying a .dex file to load custom .so libraries, aiming to call the `get_SchId() `function.

Based on the dumped content above, how can I obtain all instance objects and successfully invoke `get_SchId()`?

![微信图片_20241123183420](https://github.com/user-attachments/assets/03fb96ea-9319-44bf-ade8-3098e416a8bc)

![微信图片_20241123183425](https://github.com/user-attachments/assets/07f4fa69-cd26-420c-8628-63c348c316e5)

**Comment by BNM-Dev** [comment]
There are some ways:
1. Find place where each one created and got them from here.
2. Find place where each one stored and got them from here.
3. Hook `.ctor` (constructor) to get all of them, when it created.

**Comment by 1SUUU2** [comment]
Original words from dump developer
> This game uses hybridclr, there's not much you can do
> No hooking 
> No patching

Recommended this project but don't know how to use it,
Can you provide the code?

**Comment by BNM-Dev** [comment]
I never modded game with it, but I definitely think that this is possible to hook code in it. Plus hybridclr ([GitHub](https://github.com/focus-creative-games/hybridclr)) is open source so you can analyze its code to find out how to hook sth. After quick look into code, `BNM::InvokeHook` may work if method is calling from `hotfix.dll`
