### ISSUE TITLE
TryLoadByJNI crash

### ISSUE THREAD

**Issue by c01ns** [ByNameModding/BNM-Android#81]
BNM::Loading::TryLoadByJNI(env);
![image](https://github.com/user-attachments/assets/da004cfe-66d0-4dac-baf4-d4f23427d2b2)

![image](https://github.com/user-attachments/assets/3e600d0e-b9c9-495a-bece-4f8da306045f)

**Comment by BNM-Dev** [comment]
You set `UNITY_VER` to `213` in [GlobalSettings.hpp](https://github.com/ByNameModding/BNM-Android/blob/master/include/BNM/UserSettings/GlobalSettings.hpp)?

**Comment by zhongqingsong** [comment]
nice, thanks.
